// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4nx3DO2r7jpaCg69qWC6WT1NuCqkp3VI',
    appId: '1:1003978556725:web:85a0bc8bff3f5a13c8787c',
    messagingSenderId: '1003978556725',
    projectId: 'mynotes-testprj-flutter',
    authDomain: 'mynotes-testprj-flutter.firebaseapp.com',
    storageBucket: 'mynotes-testprj-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDYvzRAzhhoN1GwvB_kG2BOxkrexMFeS8',
    appId: '1:1003978556725:android:c474f26f79902d53c8787c',
    messagingSenderId: '1003978556725',
    projectId: 'mynotes-testprj-flutter',
    storageBucket: 'mynotes-testprj-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ3qL9xOzIyNY5tBbLxdeTSjZ7O-z7CvU',
    appId: '1:1003978556725:ios:5b6ac42e64f54ffbc8787c',
    messagingSenderId: '1003978556725',
    projectId: 'mynotes-testprj-flutter',
    storageBucket: 'mynotes-testprj-flutter.appspot.com',
    iosClientId: '1003978556725-aeimd7rpt1afrjkvfteggq3flvmkenuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
